### ISSUE TITLE
Should skip branch name checking for empty repo?

### ISSUE THREAD

**Issue by MaxymVlasov** [pdffiller/styleguide-hooks#14]
It's for possibility create `Initial commit` in any branch.

But how about "fixes" for Initial commit? Looks as not very good flow.

**Comment by dzirg44** [comment]
I found 2 workaround to avoid this bug.

1. When i create repository i must to create README.md , .gitignore etc. also, i think it will be work  but it looks not good for me.
2. Adding interactive question 'do you really want to commit in  the master branch' because i can in any moment disable this webhook. 

In the git workflow have 'Hot fixs' and  we can  use it  to  push to  the master branch without create any branch and merge. Only owner can makes this push. 

I think disable all features is not a right way because when i created the sample repository  without master branch i can create branch which will be 'default' if the other  branch have not be  define, after that i cannot delete this branch and  only Manuel can do  it.
:+1:  thank you for your help

**Comment by MaxymVlasov** [comment]
No longer relevant, see https://github.com/pdffiller/styleguide-hooks/issues/31#issuecomment-600771592
